# Generated by Django 4.0.4 on 2022-07-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='medico',
            name='profesion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
