# Generated by Django 4.0.4 on 2022-07-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_medico_edad_remove_medico_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Clinica',
        ),
    ]
