# Generated by Django 4.0.4 on 2022-07-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_invitados_delete_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
                ('subtitulo', models.TextField(default='', max_length=90)),
                ('cuerpo', models.TextField(default='', max_length=1000)),
                ('autor', models.CharField(default='', max_length=30)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Medico',
            new_name='Autor',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.AddField(
            model_name='invitados',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
    ]
